arreglar estilos para alert-inverse
EntrevistadorInteligente/landing-entrevistador pull request #34
Opened 2024-06-26 04:15 UTC by DylanSerkovich

## 📑 Description

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

2024-06-29 02:58 UTC, JamiltonQuintero requested changes

2024-06-29 02:58 UTC, JamiltonQuintero commented on src/app/components/inicio/home/home-interview-preview/home-interview-preview.component.html
> +              <div class="loader-1"></div>
Rey sorry no he subido mis cambios a dev ya mismo los paso pero ali implemente un loader general con un interceptor global que se dispara cada que se hace un consumo al back y tarda mas de 1 seg. Si quieres peudes remover este y validas el que yo cree a nivel global en la app

2024-06-30 16:39 UTC, DylanSerkovich commented on src/app/components/inicio/home/home-interview-preview/home-interview-preview.component.html
> +              <div class="loader-1"></div>
Se elimino el loader y se dejo el loader global

2024-07-01 01:33 UTC, JamiltonQuintero approved these changes

2024-07-01 01:33 UTC, merged